// Generated by LBA SEO & Ads Expert Tool v1.1
// Date: 2025-09-03
// Product: convertmyfile
// Markets: AU, US

/*
 * SAFETY CHECKLIST - COMPLETE BEFORE EXECUTION:
 * 1. VERIFY all landing pages are live
 * 2. CHECK budget is acceptable
 * 3. REVIEW geo targeting
 * 4. TEST in preview mode first
 */

// Script variables
var DATE_STAMP = '2025-09-03';
var PRODUCT_NAME = 'convertmyfile';
var MARKETS = ['AU', 'US'];

// Safety Constants
var SAFETY_CONFIG = {
  MAX_DAILY_BUDGET_AUD: 5,
  DEFAULT_CAMPAIGN_STATUS: 'PAUSED',
  DEVICE_TARGETING: 'desktop: 1.0, mobile: -1.0, tablet: -0.3',
  ALLOW_HIGH_BUDGET: false
};

// No URL health check results

function main() {
  try {
    Logger.log('Starting campaign creation for ' + PRODUCT_NAME);

    // Budget safety check
    var budgetLimit = SAFETY_CONFIG.MAX_DAILY_BUDGET_AUD;
    if (!SAFETY_CONFIG.ALLOW_HIGH_BUDGET && budgetLimit > 5) {
      throw new Error('Budget safety check failed. Budget exceeds limit.');
    }

    // Create campaigns
    createCampaigns();

    // Log execution summary
    Logger.log('=============================================');
    Logger.log('EXECUTION SUMMARY');
    Logger.log('Total campaigns: 4');
    Logger.log('Total ad groups: 4');
    Logger.log('Total keywords: 4');
    Logger.log('=============================================');

  } catch (error) {
    Logger.log("ERROR: " + error.toString());
    throw error;
  }
}

function createCampaigns() {

  // Campaign: LBA_convertmyfile_WebP PNG Conversion_AU
  try {
    Logger.log('Starting campaign creation: LBA_convertmyfile_WebP PNG Conversion_AU');
    
    var campaign = AdsApp.newCampaignBuilder()
      .withName('LBA_convertmyfile_WebP PNG Conversion_AU')
      .withStatus('PAUSED')
      .build()
      .getResult();

    Logger.log('Campaign created: ' + campaign.getName());

    // Create ad group using helper function
    var adGroup = createAdGroup(campaign, 'WebP PNG Conversion');
    Logger.log('Ad group created: ' + adGroup.getName());

    // Add keywords
    var keywordsAdded = 1;
    Logger.log('Keywords added: ' + keywordsAdded);
  } catch (error) {
    Logger.log("ERROR: Campaign creation failed - " + error.toString());
    throw error;
  }

  // Campaign: LBA_convertmyfile_PDF to JPG Tools_AU
  try {
    Logger.log('Starting campaign creation: LBA_convertmyfile_PDF to JPG Tools_AU');
    
    var campaign = AdsApp.newCampaignBuilder()
      .withName('LBA_convertmyfile_PDF to JPG Tools_AU')
      .withStatus('PAUSED')
      .build()
      .getResult();

    Logger.log('Campaign created: ' + campaign.getName());

    // Create ad group using helper function
    var adGroup = createAdGroup(campaign, 'PDF to JPG Tools');
    Logger.log('Ad group created: ' + adGroup.getName());

    // Add keywords
    var keywordsAdded = 1;
    Logger.log('Keywords added: ' + keywordsAdded);
  } catch (error) {
    Logger.log("ERROR: Campaign creation failed - " + error.toString());
    throw error;
  }

  // Campaign: LBA_convertmyfile_WebP PNG Conversion_US
  try {
    Logger.log('Starting campaign creation: LBA_convertmyfile_WebP PNG Conversion_US');
    
    var campaign = AdsApp.newCampaignBuilder()
      .withName('LBA_convertmyfile_WebP PNG Conversion_US')
      .withStatus('PAUSED')
      .build()
      .getResult();

    Logger.log('Campaign created: ' + campaign.getName());

    // Create ad group using helper function
    var adGroup = createAdGroup(campaign, 'WebP PNG Conversion');
    Logger.log('Ad group created: ' + adGroup.getName());

    // Add keywords
    var keywordsAdded = 1;
    Logger.log('Keywords added: ' + keywordsAdded);
  } catch (error) {
    Logger.log("ERROR: Campaign creation failed - " + error.toString());
    throw error;
  }

  // Campaign: LBA_convertmyfile_PDF to JPG Tools_US
  try {
    Logger.log('Starting campaign creation: LBA_convertmyfile_PDF to JPG Tools_US');
    
    var campaign = AdsApp.newCampaignBuilder()
      .withName('LBA_convertmyfile_PDF to JPG Tools_US')
      .withStatus('PAUSED')
      .build()
      .getResult();

    Logger.log('Campaign created: ' + campaign.getName());

    // Create ad group using helper function
    var adGroup = createAdGroup(campaign, 'PDF to JPG Tools');
    Logger.log('Ad group created: ' + adGroup.getName());

    // Add keywords
    var keywordsAdded = 1;
    Logger.log('Keywords added: ' + keywordsAdded);
  } catch (error) {
    Logger.log("ERROR: Campaign creation failed - " + error.toString());
    throw error;
  }

}

function createAdGroup(campaign, name) {
  var adGroup = campaign.newAdGroupBuilder()
    .withName(name)
    .build()
    .getResult();
  return adGroup;
}

main();