blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/littlebearapps/seo-ads-expert/discussions
    about: Ask questions or start discussions about the project
  - name: Security Vulnerability
    url: https://github.com/littlebearapps/seo-ads-expert/security/advisories/new
    about: Report security vulnerabilities privately
