name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!
        Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the user need?
      placeholder: "Example: As a designer, I need to export color palettes in multiple formats, but currently only JSON is supported"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "Example: Add export options for CSS variables, SCSS, and Tailwind config formats"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: "Example: I could manually convert JSON to CSS, but this is time-consuming and error-prone"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my workflow)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, I can help with testing"
        - "Yes, I can help with documentation"
        - "No, but I can provide feedback"
        - "No contribution"
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or examples from other tools
      placeholder: Drag and drop images here or paste URLs to similar features in other tools
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be helpful
      placeholder: |
        1. When designing a new website theme, I export colors to Tailwind config
        2. When collaborating with developers, I share SCSS variables
        3. When maintaining design systems, I need consistent color formats
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Who would benefit from this feature? How many users?
      placeholder: "Example: All designers using Tailwind CSS (estimated 30% of users based on survey)"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
      placeholder: "Example: This feature is common in competitors like Coolors and Adobe Color"
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues and PRs to ensure this isn't a duplicate
          required: true
        - label: I have clearly described the problem this feature solves
          required: true
        - label: This feature aligns with the project's scope (3 core features max)
          required: false
